lineageNameMapping:
  hasLineage: geregistreerdMet
  ObjectLineage: Registratie
  orchestratedProperties: bestaatUit
  OrchestratedProperty: GeorkestreerdGegeven
  SourceProperty: Brongegeven
  ObjectReference: Object
  subject: onderwerp
  property: kenmerk
  value: waarde
  objectKey: identificatie
  objectType: type

sourceRelations:
  - sourceType: bgt:Pand
    property:
      name: gerelateerdBagPand
      target: bag:Pand
      cardinality: 0..1
      inverseName: gerelateerdBgtPand
      inverseCardinality: 0..1
      keyMapping:
        identificatie: identificatieBAGPND
#  - sourceType: bgt:Pand
#    property:
#      name: gerelateerdBagPandGeo
#      target: bag:Pand
#      cardinality: 0..1
#      inverseName: gerelateerdBgtPandGeo
#      inverseCardinality: 0..1
#      filterMappings:
#        - property: geometrie
#          operator:
#            type: intersects
#          sourcePath: geometrie2dGrondvlak

objectTypeMappings:
  Adres:
    sourceRoot: bag:Nummeraanduiding
    propertyMappings:
      identificatie:
        pathMappings:
          path: identificatie
      huisnummer:
        pathMappings:
          path: huisnummer
      huisnummertoevoeging:
        pathMappings:
          path: huisnummertoevoeging
      huisletter:
        pathMappings:
          path: huisletter
      postcode:
        pathMappings:
          path: postcode
      straatnaam:
        pathMappings:
          path: ligtAan/naam
      plaatsnaam:
        pathMappings:
          path: ligtIn/naam
          andThen:
            path: ligtAan/ligtIn/naam
            ifMatch:
              type: isNull
      isHoofdadres:
        pathMappings:
          path: isHoofdadresVan/identificatie
          map:
            type: cel
            options:
              expr: 'type(result) != null_type'
      omschrijving:
        pathMappings:
          - path: ligtAan/naam
          - path: huisnummer
            map:
              type: prepend
              options:
                prefix: ' '
          - path: huisletter
            map:
              type: prepend
              options:
                prefix: ' '
          - path: huisnummertoevoeging
            map:
              type: prepend
              options:
                prefix: '-'
          - path: postcode
            map:
              type: prepend
              options:
                prefix: ', '
          - path: ligtIn/naam
            andThen:
              path: ligtAan/ligtIn/naam
              ifMatch:
                type: isNull
            map:
              type: prepend
              options:
                prefix: ' '
        combiner:
          type: join
      # TODO: auto-generatie inverse mappings
      isAdresVanGebouw:
        pathMappings:
          path: isHoofdadresVan/maaktDeelUitVan/gerelateerdBgtPand

  Gebouw:
    sourceRoot: bgt:Pand
    propertyMappings:
      identificatie:
        pathMappings:
          path: identificatie
      bouwjaar:
        pathMappings:
          path: gerelateerdBagPand/oorspronkelijkBouwjaar
      bovenaanzichtgeometrie:
        pathMappings:
          path: gerelateerdBagPand/geometrie
      maaiveldgeometrie:
        pathMappings:
          path: geometrie2dGrondvlak
      heeftAlsAdres:
        pathMappings:
          - path: gerelateerdBagPand/bevat/heeftAlsHoofdadres
          - path: gerelateerdBagPand/bevat/heeftAlsNevenadres
        combiner:
          type: merge
      totaalPerceelOppervlak:
        pathMappings:
          path: gerelateerdBagPand/bevat/heeftAlsHoofdadres/betreftInverse/heeft/kadastraleGrootte
        combiner:
          type: sum
      bevindtZichOpPerceel:
        pathMappings:
          path: gerelateerdBagPand/bevat/heeftAlsHoofdadres/betreftInverse/heeft

  Perceel:
    sourceRoot: brk:Perceel
    propertyMappings:
      identificatie:
        pathMappings:
          path: identificatie
      laatsteKoopsom:
        pathMappings:
          path: koopsom
      oppervlak:
        pathMappings:
          path: kadastraleGrootte
      begrenzing:
        pathMappings:
          path: begrenzing
