logging:
  level:
    root: INFO

spring:
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.graphql.GraphQlAutoConfiguration
  graphql:
    graphiql:
      enabled: true

management:
  server:
    port: 8081
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus

orchestrate:
  gateway:
    targetModel: imxgeo
    mapping: /config/imxgeo.yaml
    sources:
      bag:
        type: ogcapi
        options:
          #landingPage: http://localhost:7080/rest/services/bag
          landingPage: https://wau.ldproxy.net/bag
          limit: 15
          supportsPropertySelection: true
          supportsRelProfiles: true
      bgt:
        type: ogcapi
        options:
          #landingPage: http://localhost:7080/rest/services/bgt
          landingPage: https://wau.ldproxy.net/bgt
          limit: 15
          supportsPropertySelection: true
          supportsRelProfiles: true
