logging:
  level:
    root: INFO

spring:
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.graphql.GraphQlAutoConfiguration
  graphql:
    graphiql:
      enabled: true

management:
  server:
    port: 8081
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus

orchestrate:
  gateway:
    targetModel: ADRES #${TARGET_MODEL:adres}
    mapping: /config/imxgeoMapping.yaml # ${MODEL_MAPPING:/config/imxgeoMapping.yaml}
    dataPath: /data # ${DATA_PATH:./data}
